shayonj/pg_easy_replicate

- .github/workflows/ci.yaml
- docker-compose.yml
- lib/pg_easy_replicate.rb
- spec/database_helpers.rb
- spec/pg_easy_replicate/query_spec.rb
Also supports `'` in password.
New unescaped password for CI: `jamesbond123@7!'3aaR`
Fixes: https://github.com/shayonj/pg_easy_replicate/issues/16
> Support password with special chars and test for url encoded URI

- README.md
- lib/pg_easy_replicate.rb
- lib/pg_easy_replicate/cli.rb
- lib/pg_easy_replicate/helper.rb
- lib/pg_easy_replicate/orchestrate.rb
- lib/pg_easy_replicate/stats.rb
- spec/database_helpers.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
- spec/pg_easy_replicate/query_spec.rb
- spec/pg_easy_replicate_spec.rb
`CREATE SUBSCRIPTION` requires that the user is superuser, which is why we require the user for source and target url/con string to be `superuser`. However, AWS and GCP don't have a `superuser` role but expose dedicated roles that act as super user (`rds_superuser` and `cloudsqlsuperuser`) and can perform `create subscription`. 
This PR now supports passing such user role during `bootstrap` and `config_check`. We then accordingly ensure that the internal user we create for replication has been granted the passed in `special_user_role` accordingly. Its a little hard to write spec for since we still need grantee role to be superuser when creating subscription. IOW, hard to re-create the same scenario that AWS / GCP have created in their version of PostgreSQL and exposed custom roles like …
> Support AWS and GCP special user scenarios

- Dockerfile
- README.md
- lib/pg_easy_replicate.rb
- lib/pg_easy_replicate/cli.rb
- scripts/e2e-bootstrap.sh
- scripts/e2e-start.sh
- spec/database_helpers.rb
- spec/pg_easy_replicate/group_spec.rb
- spec/pg_easy_replicate_spec.rb
- spec/spec_helper.rb
By passing --copy_schema to boostrap, pg_easy_replicate will now automatically copy schema between the source and target database by via pg_dump. pg_dump should exist on the host machine (or container image, will be in the official image) in order for it to work
closes: https://github.com/shayonj/pg_easy_replicate/issues/4
> Introduce --copy-schema via pg_dump

- lib/pg_easy_replicate/orchestrate.rb
Limit #list_all_tables to only return tables of type BASE TABLE.
This will exclude database views, foreign tables and temporary tables from the list, which cannot be replicated.
> Exclude views, temporary tables and foreign tables from #list_all_tables

- lib/pg_easy_replicate/helper.rb
- lib/pg_easy_replicate/orchestrate.rb
- lib/pg_easy_replicate/query.rb
Add a helper method #quote_identifier for quoting unusual sql identifiers. Apply method to identifiers in DDL statements.
Rationale:
I'm working on a multi-tenanted app that uses UUIDs in the schema names, so I need to add quoting around the schema names for the generated DDL to be valid.
> Add quote_identifier helper for SQL identifiers.

- lib/pg_easy_replicate.rb
- lib/pg_easy_replicate/helper.rb
- lib/pg_easy_replicate/orchestrate.rb
- lib/pg_easy_replicate/query.rb
DB user name can contain special allowed character. Not wrapping them in escaped quotes result in syntax error
fixes: https://github.com/shayonj/pg_easy_replicate/issues/41
> Escape db user name in queries

- lib/pg_easy_replicate.rb
This was missed when running a rubocop auto-correct over `$?`. Hence, fixing now by requiring English which containers `$CHILD_STATUS`
fixes: https://github.com/shayonj/pg_easy_replicate/issues/38
related: https://github.com/rubocop/rubocop/issues/1747
> Require english lib so that $CHILD_STATUS is loaded

- .github/workflows/ci.yaml
- .github/workflows/smoke.yaml
- docker-compose.yml
- lib/pg_easy_replicate.rb
- scripts/e2e-bootstrap.sh
- scripts/e2e-start.sh
- spec/database_helpers.rb
- spec/pg_easy_replicate/group_spec.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
- spec/pg_easy_replicate/query_spec.rb
- spec/pg_easy_replicate/stats_spec.rb
- spec/pg_easy_replicate_spec.rb
- spec/smoke_spec.rb
Follow up to https://github.com/shayonj/pg_easy_replicate/pull/42.
Using `james-bond` instead of `jamesbond` in specs to test for cases where username can contain
special chars.
> Quote indent username, dbname and schema in all places

- lib/pg_easy_replicate.rb
- spec/pg_easy_replicate_spec.rb
Its possible for there to be hangover from previous failed runs where the internal user may exist in the DB. When that happens, the bootstrap shouldn't fail but attempt to revoke privileges and drop the user, to start fresh again.
https://github.com/shayonj/pg_easy_replicate/issues/73
> Drop existing user with privileges when bootstrapping

- .github/workflows/ci.yaml
- .github/workflows/smoke.yaml
- docker-compose.yml
- lib/pg_easy_replicate.rb
- scripts/e2e-bootstrap.sh
- scripts/e2e-start.sh
- spec/database_helpers.rb
Also support use custom DB name with a `-` as proxy checks
https://github.com/shayonj/pg_easy_replicate/issues/73
> Quote indent DB name

- lib/pg_easy_replicate/index_manager.rb
- spec/database_helpers.rb
- spec/pg_easy_replicate/index_manager_spec.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
Droping unique indices is not possible w/o having to drop and recreate the constraint.
We could in future consider doing that if there are significant performance gains. Otherwise, just don't attempt to drop/recreate it.
We'd still gain on the performance improvement from having dropped other indices before copy
https://github.com/shayonj/pg_easy_replicate/issues/8#issuecomment-1901783088
> Don't attempt to drop and recreate unique indices

- lib/pg_easy_replicate.rb
- lib/pg_easy_replicate/cli.rb
- lib/pg_easy_replicate/helper.rb
- lib/pg_easy_replicate/index_manager.rb
- lib/pg_easy_replicate/orchestrate.rb
- spec/pg_easy_replicate/index_manager_spec.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
- spec/pg_easy_replicate_spec.rb
- config check now performs an additional check to ensure all tables replicating (or about to be) have some form of replica identity setup. This way, if when the subscription starts, it doesn't fail hard if the one of the tables cannot be replicate. This usually involves having a PK, index or FULL REPLICA identity
- Bug fix with drop indices when custom set of tables are passed
- Refactor a bit of tables list is derived
> Extend config check to assert for REPLICA IDENTITY on tables and drop index bug fix

- lib/pg_easy_replicate/helper.rb
In order to list tables suitable for replication we should select tables with `relpersistence = 'p'` omitting `UNLOGGED` tables, which are listed as `BASE TABLE` in `information_schema.tables`
> List only permanent tables

- lib/pg_easy_replicate/orchestrate.rb
Table name could use reserved keyword from SQL. For example, the following is valid
```SQL
create table "table" (id int);
insert into "table" (id) values (1);
select * from "table"
```
NOTE the quoting
> Quote table name in the `VACUUM` SQL

- lib/pg_easy_replicate/helper.rb
- lib/pg_easy_replicate/orchestrate.rb
- spec/database_helpers.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
PostGIS creates `spatial_ref_sys` table which should never be replicated
> Exclude tables created by extensions

- README.md
- lib/pg_easy_replicate.rb
- lib/pg_easy_replicate/cli.rb
- lib/pg_easy_replicate/helper.rb
- lib/pg_easy_replicate/orchestrate.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
- spec/pg_easy_replicate_spec.rb
Proposal to add `exclude_tables` which does the opposite of the cmd `--tables, -t` in that it excludes comma separated table names from the replication sync if specified.
PR adds the following:
- cli integration using `--exclude_tables` / `--e`
- Logic to handle removal of specified table names from sync 
- Validation to abort if `--tables` and `--exclude_tables` are specified together
- Test coverage for `exclude_tables`
> Proposal : Add cmd to exclude tables from sync

- .github/workflows/ci.yaml
- Gemfile.lock
- README.md
- docker-compose.yml
- lib/pg_easy_replicate.rb
- lib/pg_easy_replicate/cli.rb
- lib/pg_easy_replicate/ddl_audit.rb
- lib/pg_easy_replicate/ddl_manager.rb
- lib/pg_easy_replicate/orchestrate.rb
- pg_easy_replicate.gemspec
- scripts/e2e-start.sh
- spec/database_helpers.rb
- spec/pg_easy_replicate/ddl_audit_spec.rb
- spec/pg_easy_replicate/ddl_manager_spec.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
- spec/smoke_spec.rb
`pg_easy_replicate` now includes a DDL tracking for most common DDL operations (`ALTER`, `CREATE INDEX`/`DROP INDEX`) allowing users to monitor and apply schema changes between source and target databases during the replication process. `pg_easy_replicate` won't automatically apply the changes (feature request welcome). For now, it exposes the ability to list and apply DDL changes. 
1. DDL Tracking:
- Enabled with the `--track-ddl` during `start_sync`.
- Uses PostgreSQL event triggers to capture DDL events (`ALTER`, `CREATE INDEX`/`DROP INDEX`) on specified tables.
- Stores DDL changes in a dedicated audit table (`pger_ddl_audits`) within an internal schema.
2. Listing DDL Changes:
- Command: `pg_easy_replicate list_ddl_changes -g <group-name> [-l <limit>]`
- Displays recent DDL changes …
> Support DDL Tracking

- README.md
- lib/pg_easy_replicate/cli.rb
- lib/pg_easy_replicate/stats.rb
- spec/pg_easy_replicate/stats_spec.rb
PR adds the following:
- cli integration using `--notify` (includes support for configuring` --group_name, --url, --frequency, --timeout`)
- Logic to handle pushing stats notifications to a https endpoint on a loop using timeout and frequency 
- Test coverage for notify
- README updates on how to use the new command
> Proposal: add notify command to send stats results to an endpoint

- README.md
When I executed the migration for only a small subset of tables, I did notice that it would error out if there were spaces in the list of tables.  Just updating the example to reflect no spaces are needed.  And I saw the track-ddl command was missing a dash at the front.
> fixed typo, removed spaces from tables list example

- lib/pg_easy_replicate/orchestrate.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
During testing of `stop_sync` I encountered the following error when it tries to drop the subscription:
`PG::InsufficientPrivilege: ERROR: must be owner: pg_subscription_zdt_migration_test`
I noticed that we specify the user to create the subscription but it was not assuming this user to drop it afterwards causing the above error.
> added correct user to stop_sync drop of subscription

- lib/pg_easy_replicate/orchestrate.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
Also switch the order, so that vacuum analyze is the last thing that happens since it can take time.
> Do not mark switchover complete if subscription drop fails

- lib/pg_easy_replicate/group.rb
- spec/pg_easy_replicate/group_spec.rb
- spec/pg_easy_replicate/orchestrate_spec.rb
This way we don't attempt to recreate indices post switchover (no-op anyways)
> Ensure default for recreate_indices_post_copy is always false (match cli default)
